### ISSUE TITLE
Deployment target 9.3

### ISSUE THREAD

**Issue by bzdybowicz** [iosdevzone/IDZSwiftCommonCrypto#44] opened 2016-10-13 14:09 UTC
Why was deployment target bumped to 9.3 in version 0.8.3? Version 0.8.1 was made to work with swift 2.3, but it does not goes through 'Running prepare_command'. Version 0.8.3 works, but it requires deployment target 9.3, which is pretty damn high according that newest iOS released is 10.0.2. 

I can also see that project/targets deployment target did not change. It is just pod spec requirement, my question is: why is this bumped so high?

**Comment by iosdevzone** [comment] 2016-10-13 17:28
To be quite honest it was accidental (the deployment target being bumped so high). Getting the podspec to work at all took quite some time. It repeatedly failed `pod lib lint` due to some weird Cocoapods paths issue; even the current working podspecs will fail `lib lint`. There was some discussion on Cocoapods boards that this was due to deployment target settings so in trying to get a working spec I was bumping it, however I think the problem is some difference between `lib lint` and `spec lint`. I doubt I'll have time anytime soon to see if the pods will work with a earlier deployment target. If you do and can test that library passes all tests on an earlier OS please send me a pull request. I hate marking things as wontfix but for the moment given my time constraints that's how I'll have to disposition this one.

**Closed by iosdevzone** 2016-10-13 17:28 UTC
Labels: wontfix
