### ISSUE TITLE
OSX Compatibility

### ISSUE THREAD

**Issue by thanegill** [iosdevzone/IDZSwiftCommonCrypto#7] opened 2015-11-08 04:31 UTC
Can this project become OS X Compatible? Would it be as easy as adding OS X to the podspec?

**Comment by iosdevzone** [comment] 2015-11-10 22:20
This should be doable. To do it properly the module map generation script should be changed, but there is nothing in the Swift code that is iOS-specific. I'd be delighted with a pull request if you want to take a crack at it. It'll be a few days before I get to it.

**Comment by iosdevzone** [comment] 2016-01-08 19:23
I've started adding support for OS X, tvOS and watchOS. Commit 5dda539b30e69b121eb6974a1ce21c145224c2eb contains targets for all platforms and tests for all but watchOS. There is still some work to do to make CocoaPods support this.

**Comment by iosdevzone** [comment] 2016-01-09 00:33
I have just merge PR #12 which adds support for OS X, watchOS, and tvOS. I will soon tag and release this and push an update to CocoaPods.

**Comment by iosdevzone** [comment] 2016-01-12 18:09
Fixed in version 0.7.0 / PR#12

**Closed by iosdevzone** 2016-01-12 18:09 UTC
Labels: enhancement

**Comment by PanosSakkos** [comment] 2016-10-02 12:44
Hi @iosdevzone ,

I tried to install the pod in project that supports both iOS and macOS and I got the following error:

>Ghosts-MacBook-Pro:dono-pod ghost$ pod install
Analyzing dependencies
[!] The platform of the target `DonoCoreMac` (OS X 10.9) is not compatible with `IDZSwiftCommonCrypto (0.6.8)`, which does not support `osx`.

**Comment by PanosSakkos** [comment] 2016-10-02 21:01
Seems like if you don't specify the pod version that you want, then it tries to install the earliest version.
And in this case the earliest version didn't support osx.
I resolved the issue by specifying the 0.9.0 version in my podfile.
Will open a PR on the readme for that.

**Comment by iosdevzone** [comment] 2016-10-02 21:08
Thanks for tracking down the root cause. I'll merge the PR and push it out in the next release. There are some other documentation issues that I would like to deal with before pushing the next release.
