### ISSUE TITLE
 `no such module CommonCrypto` when install via Carthage

### ISSUE THREAD

**Issue by huy-le** [iosdevzone/IDZSwiftCommonCrypto#43] opened 2016-10-13 02:01 UTC
Hi,
- I use latest Carthage v0.18.1.
- And your library is v0.9.0.
- XCode 8.
- xcode-select is XCode 8.

I create a independent cartfile what is dedicated for `IDZSwiftCommonCrypto`. Then run `carthage update --verbose`. It cannot build because the `import CommonCrypto` - `no such module CommonCrypto`

I open .xcodeproj and try build, but there is same error. Could you give me some glue to solve this?

Cheers,

**Comment by bzdybowicz** [comment] 2016-10-13 11:23
Same on cocoa pods with version 0.8.1

**Comment by iosdevzone** [comment] 2016-10-13 17:32
@bzdybowicz The problem with Cocoapods v0.8.1 was addressed in issue #33. Please don't post Cocoapods problems on a Carthage issue. It makes it really tricky to keep track of things. Thanks!

**Comment by iosdevzone** [comment] 2016-10-13 17:43
@huy-le Apologies, in the push to get a bunch of new releases out Carthage did not get much attention.

The problem you are seeing is probably caused by the project not being able to find the fake CommonCrypto module files. These files are created by the `GenerateCommonCryptoModule.swift` in a **Run Script** build phase and pointed to by setting the Framework Search Path in the project build settings to `$(PROJECT_DIR)/Frameworks/$(PLATFORM_NAME)`.

I'll try to look at it in the next few days, but have very limited time at the moment. Hopefully the clues above will help you get up and running.

**Comment by iosdevzone** [comment] 2016-10-13 20:42
@hu-le would you please send the output of `carthage update --verbose` and also let me know what version of OS X/macOS you are using. I am not able to reproduce your problem here.  There is a repository I use for the Carthage testing [IDZSwiftCommonCryptoCarthageTest](https://github.com/iosdevzone/IDZSwiftCommonCryptoCarthageTest). Perhaps you could try that and tell me if you also experience the problem with that project. This should help me narrow down the issue.

**Comment by iosdevzone** [comment] 2016-12-18 11:58
Closing due to lack of response.

**Closed by iosdevzone** 2016-12-18 11:58 UTC
Labels: bug
