### ISSUE TITLE
Carthage Build fails for IDZSwiftCommonCrypto

### ISSUE THREAD

**Issue by priyapy** [iosdevzone/IDZSwiftCommonCrypto#24] opened 2016-05-11 12:25 UTC
Carthage is not getting build for IDZSwiftCommonCrypto. Following is the error i am getting. 

The following build commands failed:
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Utilities.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Status.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Crypto.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Cryptor.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/StreamCryptor.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Updateable.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Random.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
/Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift:10:8: error: no such module 'CommonCrypto'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto.xcworkspace -scheme IDZSwiftCommonCrypto (Release) -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Utilities.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/KeyDerivation.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Status.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Crypto.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Cryptor.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/StreamCryptor.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Updateable.swift
	CompileSwift normal arm64 /Users/MyComputer/Documents/ - iOS/10 May/XXXXX/Carthage/Checkouts/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/Random.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)

Some body please help me

**Comment by iosdevzone** [comment] 2016-05-11 17:53
Hi priyapy, What version of Xcode, OS X and Carthage are you using?

**Comment by priyapy** [comment] 2016-05-12 01:04
I am using xcode 7.3.1 . El captain carthage0.16.2

**Comment by iosdevzone** [comment] 2016-05-13 19:24
I am having difficulty reproducing the problem. I wonder if the presence of the path element " - iOS" in your paths is to blame? Paths containing spaces or '-' characters confuse some command line tools.

**Comment by priyapy** [comment] 2016-05-15 19:17
Sure i ll try this

**Comment by priyapy** [comment] 2016-05-17 06:01
Thank you for the prompt response. It worked well.

**Comment by priyapy** [comment] 2016-05-17 12:39
But getting error as Missing required module 'Common Crypto' when using in another device

**Comment by iosdevzone** [comment] 2016-05-17 19:24
Hi there, sorry you're still having trouble. I am not sure I understand what you mean by "when using in another device" can you explain a little more please? For example, were you attempting to compile or attempting to run when you saw this message? 

Also please copy & paste or attach original log file or error messages... It seems a little strange that there is a space in 'Common Crypto' in your message, unless it is a typo.

Hopefully I can get you up and running soon.

Thanks for your patience,
ids

**Comment by priyapy** [comment] 2016-05-18 15:28
I am using this particular idzswiftcommoncrypt in a dynamic framework. While i am referring that framework from an external project i am getting error "missing required module 'CommonCrypto'". Why is it like that.

**Comment by iosdevzone** [comment] 2016-05-18 19:07
Hi,
Without a build log I really don't have enough information to help you any further. Please attach a build log or post a minimal project that reproduces the problem somewhere.
This is not a build problem with IDZSwiftCommonCrypto, it is an issue in the build configuration of your dynamic framework build. 
ids

**Comment by priyapy** [comment] 2016-05-18 19:22
Can u clarify one thing? Y do we need to create a fake module map for common crypto while installing it manually

**Comment by iosdevzone** [comment] 2016-05-18 19:29
Apple does not provide a module map for CommonCrypto because there is no CommonCrypto.framework. The routines are part of the System framework. The fake module map serves to make the routines visible to Swift. It should only be needed during the compilation of IDZSwiftCommonCrypto. After that the linker will just resolve the CommonCrypto routines to the ones in System. Somehow your project seems to think it needs CommonCrypto; not sure why.

**Comment by priyapy** [comment] 2016-05-19 17:35
Ok, but i believe we need to do this step only for manual implementation. 
Currently I am using this in my dynamic framework. So I am attaching the error which i am facing when i am using my framework in a project application
<img width="1117" alt="screenshot 2016-05-19" src="https://cloud.githubusercontent.com/assets/15901889/15403320/0c1f9f00-1e16-11e6-8339-6d664adb03ce.png">

**Comment by iosdevzone** [comment] 2016-05-19 20:11
HI there, without a project to reproduce it I really can't help you any further. Closing this issue for the moment. If you can provide an example project I will reopen it.

**Closed by iosdevzone** 2016-05-19 20:11 UTC
Labels: question
